# Generated by Django 4.1 on 2022-08-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_creator_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('framework', models.ManyToManyField(to='relations.framework')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
